jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  oast-frontend:
    machine: true
    steps:
      - checkout

      - run:
          name: Install npm packages
          command: npm install

      - run:
          name: Run RetireJS
          command: |
            docker run --rm -v $(pwd):/src -w /src hysnsec/retire --outputformat json --outputpath retirejs-output.json --severity high
          when: on_fail

      - store_artifacts:
          path: retirejs-output.json
          destination: retirejs-artifact
          when: always

  oast:
    machine: true
    steps:
      - checkout

      - run:
          command: docker run -v $(pwd):/src --rm hysnsec/safety check -r /src/requirements.txt --json | tee oast-results.json
          when: on_fail

      - store_artifacts:
          path: oast-results.json
          destination: safety-artifact
          when: always

  oast-snyk:
    docker:
      - image: node:alpine3.10
    steps:
      - checkout

      - run: 
          command: |
            wget -O snyk https://github.com/snyk/cli/releases/download/v1.1156.0/snyk-alpine
            chmod +x snyk
            mv snyk /usr/local/bin/
            npm install
            snyk auth $SNYK_TOKEN
            snyk test --json > snyk-results.json || true

      - store_artifacts:
          path: snyk-results.json
          destination: snyk-artifact
          when: always

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          when: on_fail

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step"

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build
      - oast-frontend:
          requires:
            - test
      - oast:
          requires:
            - test
      - integration:
          requires:
            - oast
            - oast-frontend
            - oast-snyk
      - prod:
          type: approval
          requires:
            - integration
